### ISSUE TITLE
Running `remark README.md` results in this error. 

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/js-objects-this#41]
```sh
README.md
  1:1  error  TypeError: Cannot read property 'use' of null
    at lint (/Users/Benjamski/.nvm/versions/node/v6.10.0/lib/node_modules/remark-lint/index.js:11:7)
    at Function.use (/Users/Benjamski/.nvm/versions/node/v6.10.0/lib/node_modules/remark/node_modules/unified/index.js:318:25)
    at /Users/Benjamski/.nvm/versions/node/v6.10.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/file-pipeline/configure.js:117:19
    at /Users/Benjamski/.nvm/versions/node/v6.10.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:444:7
    at Array.forEach (native)
    at /Users/Benjamski/.nvm/versions/node/v6.10.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:443:13
    at /Users/Benjamski/.nvm/versions/node/v6.10.0/lib/node_modules/remark-cli/node_modules/unified-engine/lib/configuration.js:327:5
    at /Users/Benjamski/.nvm/versions/node/v6.10.0/lib/node_modules/remark-cli/node_modules/vfile-find-up/index.js:135:9
    at FSReqWrap.oncomplete (fs.js:123:15)

✖ 1 error
```

I'm not sure what's causing this, but I wanted to open an issue in case I'm unable to resolve it before delivery.

**Comment by gaand** [comment]
There is an ongoing problem getting remark-lint to function properly for any repositorie.
